### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by ewlusky** [pepebecker/pinyin-rest#3]
Been getting a 502 error all day, if you're taking the server down I understand but it seems like pretty bad luck as I am supposed to demo an app that uses this API tomorrow.

**Comment by pepebecker** [comment]
@ewlusky, sorry to hear that. I'm not sure why the server went down. It's back up now

**Comment by ewlusky** [comment]
I faked it for the demo, bit of bad luck but thanks for putting it back up.
