### ISSUE TITLE
Website/server down

### ISSUE THREAD

**Issue by THEH0P** [pepebecker/pinyin-rest#6]
I've tried pinging your website and it's giving me a 404 error

**Comment by pepebecker** [comment]
@thehoppa sorry for the inconvenience. I updated the domain to https://api.pinyin.pepe.asia.
I just added the old domain so now it should work like before.

**Comment by THEH0P** [comment]
Hey thanks. Now that the new domain is up I've updated my stuff so it pings
the new domain. Thanks for keeping it going!
